services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dXknlwUUAkDVwe808ENHoZANke2IWvr9
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server
    environment:
      REDIS_PASSWORD: NNf0mxPLI1ucX0EmcldbwhYi9Mjk1FjU
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
